### ISSUE TITLE
IDE Installation Error

### ISSUE THREAD

**Issue by tsheik** [learn-co-curriculum/accelerated-bootcamp-prep-welcome#1]
Hi, I tried to install the IDE on Intel ATOM. However installation stopped midway with an error. I have the log file if someone wants to look at it. If its a platform limitation then let me know, I will find another computer to install IDE.

**Comment by aviflombaum** [comment]
@tsheik Thanks for the report - the best place to raise this is actually emailing support@learn.co - going to close this for now.
